# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('job_title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/speaker')),
                ('speaker_type', models.CharField(choices=[('n', 'Normal'), ('k', 'Keynote')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/sponsor')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SponsorType'),
        ),
    ]
