# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180205_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
