version: '2'

services:
    web:
        restart: always
        build:
          context: ../
        image: pycon2018-web
        volumes:
          - ../:/srv/funny/pycon2018
        container_name: pycon2018-web
        working_dir: "/srv/funny/pycon2018"
        command: scripts/docker_startup.sh
        ports:
          - "2329:22"

    nginx:
        restart: always
        build:
            context: ../
            dockerfile: DockerfileNginx
        image: pycon2018-nginx
        container_name: pycon2018-nginx
        volumes_from:
            - web
        links:
            - web
        ports:
            - "80:80"
            - "443:443"
