version: '2'

services:
    jomari-web:
        restart: always
        build:
          context: ../
        image: pycon2018-web:1.0
        volumes:
          - ../:/srv/funny/pycon2018
        container_name: pycon2018-web-jomari
        working_dir: "/srv/funny/pycon2018"
        command: scripts/docker_startup.sh
        ports:
          - "2330:22"

    nginx:
        restart: always
        build:
            context: ../
            dockerfile: DockerfileNginx
        image: pycon2018-nginx
        container_name: pycon2018-nginx-jomari
        volumes_from:
            - jomari-web
        links:
            - jomari-web
        ports:
            - "8000:80"
            - "8001:443"

