# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='reviewed_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
